- name: "Backup Old Certs"
  shell:
    mv ssl ssl-`date "+%Y-%m-%d~%H:%M:%S"` && mkdir ssl
  args:
    chdir: "{{ workdir }}"
  when: (CERT_POLICY) == "update"

- name: "Generate ca-config.json"
  template:
    src: ca-config.json.j2
    dest: "{{ cert_root_dir }}/ca-config.json"
    
- name: "Generate ca-csr.json"
  template:
    src: ca-csr.json.j2
    dest: "{{ cert_root_dir }}/ca-csr.json"

- name: "Generate CA File and Key File"
  shell:
    cfssl gencert -initca ca-csr.json | cfssljson -bare ca -
  args:
    chdir: "{{ cert_root_dir }}"

- name: "Generate server-csr.json"
  template:
    src: server-csr.json.j2
    dest: "{{ cert_root_dir }}/server-csr.json"

- name: "Generate Server Certs File and Key File"
  shell:
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes server-csr.json | cfssljson -bare server
  args:
    chdir: "{{ cert_root_dir }}"

- name: "Generate admin-csr.json"
  template:
    src: admin-csr.json.j2
    dest: "{{ cert_root_dir }}/admin-csr.json"

- name: "Generate Admin Certs File and Key File"
  shell:
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json | cfssljson -bare admin
  args:
    chdir: "{{ cert_root_dir }}"

- name: "Generate kube-proxy-csr.json"
  template:
    src: kube-proxy-csr.json.j2
    dest: "{{ cert_root_dir }}/kube-proxy-csr.json"

- name: "Generate Kube-proxy Certs File and Key File"
  shell:
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: "{{ cert_root_dir }}"

- name: "Generate metrics-servery-csr.json"
  template:
    src: metrics-server-csr.json.j2
    dest: "{{ cert_root_dir }}/metrics-server-csr.json"

- name: "Generate Metrics-server Certs File and Key File"
  shell:
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes metrics-server-csr.json | cfssljson -bare metrics-server
  args:
    chdir: "{{ cert_root_dir }}"

# added by BC for k8s version since 1.20 as controller-manager or scheduler need to talk to 
# apiserver on 6443, not localhost:8080 any more
- name: "Generate kube-controller-csr.json"
  template:
    src: kube-controller-csr.json.j2
    dest: "{{ cert_root_dir }}/kube-controller-csr.json"
  when: kubernetes_version is version('1.20.0', '>=')

- name: "Generate kube contoller manager Certs File and Key File"
  shell:
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-controller-csr.json | cfssljson -bare admin
  args:
    chdir: "{{ cert_root_dir }}"
  when: kubernetes_version is version('1.20.0', '>=')

- name: "Generate kube-scheduler-csr.json"
  template:
    src: kube-scheduler-csr.json.j2
    dest: "{{ cert_root_dir }}/kube-scheduler-csr.json"
  when: kubernetes_version is version('1.20.0', '>=')

- name: "Generate kube scheduler manager Certs File and Key File"
  shell:
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-scheduler-csr.json | cfssljson -bare admin
  args:
    chdir: "{{ cert_root_dir }}"
  when: kubernetes_version is version('1.20.0', '>=')

