- name: "Copy Kube-scheduler Configuration Files"
  template:
    src: kube-scheduler.j2
    dest: "{{workdir}}/kubernetes/cfg/kube-scheduler"
    
- name: "Copy Kube-scheduler Systemd File"
  template:
    src: kube-scheduler.service.j2
    dest: /usr/lib/systemd/system/kube-scheduler.service

- name: "Copy Admin Kubeconfig to master nodes:/opt/kubernetes/cfg"
  copy:
    src: "{{ cert_root_dir }}/kube-scheduler.kubeconfig"
    dest: "{{ kube_config_dir }}/cfg"
  when: kubernetes_version is version('1.20.0', '>=') and admin_kubeconfig is failed
  # this is to make the kubectl commands not to use localhost:8080 any more

- name: "Start Kube-scheduler"
  systemd:
    name: kube-scheduler
    state: restarted
    enabled: true
    daemon-reload: true
