- name: "Make Role Labels to Masters"
  shell: |
    sleep 5
    kubectl label nodes {{ ansible_hostname }} node-role.kubernetes.io/master=
  ignore_errors: yes

- name: "Make Taints to Masters"
  shell: |
    sleep 5
    kubectl taint nodes {{ ansible_hostname }}  node-role.kubernetes.io/master=:NoSchedule
  ignore_errors: yes
