# Set system parameters
  - name: copy system parameters config file
    template:
      src: 99-k8s.conf.j2
      dest: /etc/sysctl.d/99-k8s.conf
  - name: Load system parameters
    shell: modprobe br_netfilter && sysctl -p /etc/sysctl.d/99-k8s.conf
    ignore_errors: yes
    # ignore_errors as centos8 doesn't have fs.may_detach_mounts. The result code is 255 in that case.
